FROM node:22-alpine AS builder

WORKDIR /app

COPY client/ ./

RUN npm ci
RUN npm run build

FROM nginx:stable-alpine

COPY local_conf/nginx.client.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist/ /usr/share/nginx/html

EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
